version: '3.8'
services:
  fincore-db:
    image: postgres:15-alpine
    container_name: fincore-postgres
    environment:
      POSTGRES_DB: fincoredb
      POSTGRES_PASSWORD: password123
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: